name: Build the App and create realese

on:
  release:
    type: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup app env
        run: |
          echo "APP_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "APP_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path:  ${{ env.APP_NAME}}

      - name: Get appinfo data
        id: appinfo
        uses: skjnldsv/xpath-action@7e6a7c379d0e9abc8acaef43df403ab4fc4f770c # master
        with:
          filename: ${{ env.APP_NAME }}/appinfo/info.xml
          expression: "//info//dependencies//nextcloud/@min-version"

      - name: Install Node
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
          cache: 'npm'

      - name: Build ${{ env.APP_NAME }}
        # Skip if no package.json
        if: ${{ steps.versions.outputs.nodeVersion }}
        env:
          NODE_ENV: production
        run: |
          cd ${{ env.APP_NAME }}
          npm ci
          npm run build --if-present
